# Generated by Django 6.0.6 on 2026-07-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fruit', 'Fruit'), ('drink', 'Drink'), ('snack', 'Snack')], default='fruit', max_length=100),
            preserve_default=False,
        ),
    ]
